var categories = [
{"id": "103","name": "Music"},{"id": "110", "name": "Food & Drink"}, 
{"id": "113","name": "Community & Culture"}, {"id": "105", "name": "Performing & Visual Arts"}, 
{"id": "104","name": "Film, Media & Entertainment"}, {"id": "108","name": "Sports & Fitness"}, 
{"id": "107","name": "Health & Wellness"}, {"id": "102", "name": "Science & Technology" },{"id": "109", "name": "Travel & Outdoor"}, 
{"id": "111","name": "Charity & Causes"},{"id": "114","name": "Religion & Spirituality"},{"id": "115","name": "Family & Education"}, 
{"id": "116","name": "Seasonal & Holiday"},{ "id": "112","name": "Government & Politics"},{"id": "106", "name": "Fashion & Beauty"} ];

exports.categories = categories;

var listOfCategories = "Music\nFood\nCommunity\nArts\n" +
                        "Entertainment\nSports\nHealth\nTechnology\nTravel\n" +
                        "Charity\nReligion\nEducation\nHoliday\nPolitics\n" +
                        "Fashion\n";
exports.listOfCategories = listOfCategories;

var invalidMonth = [
  "januari","februari","maret","mei","juni","juli","agustus","oktober","nopember","desember"
];
exports.invalidMonth = invalidMonth;

var listCititesofIndonesian = ["Jakarta","Surabaya",
	"Bandung",
	"Medan",
	"Bekasi",
	"Semarang",
	"Tangerang",
	"Depok",
	"Palembang",
	"Tangerang",
	"Makassar",
	"Batam",
	"Pekanbaru",
	"Bogor",
	"Lampung",
	"Padang",
	"Denpasar",
	"Malang",
	"Samarinda",
	"Tasikmalaya",
	"Banjarmasin",
	"Balikpapan",
	"Bali",
	"Serang",
	"Jambi",
	"Cimahi",
	"Pontianak",
	"Surakarta",
	"Manado",
	"Mataram",
	"Cilegon",
	"Yogyakarta",
	"Ambon",
	"Kupang",
	"Palu",
	"Bengkulu",
	"Cirebon",
	"Sukabumi",
	"Jayapura",
	"Kendari",
	"Pekalongan",
	"Siantar",
	"Sorong",
	"Binjai",
	"Palangkaraya",
	"Dumai",
	"Kediri",
	"Tegal",
	"Padang Sidempuan",
	"Banda Aceh",
	"Ternate",
	"Probolinggo",
	"Lubuklinggau",
	"Banjarbaru",
	"Tarakan",
	"Bitung",
	"Tanjung Pinang",
	"Gorontalo",
	"Banjar",
	"Madiun",
	"Lhokseumawe",
	"Pasuruan",
	"Salatiga",
	"Singkawang",
	"Prabumulih",
	"Tanjung Balai",
	"Langsa",
	"Palopo",
	"Pangkal Pinang",
	"Metro",
	"Tebing Tinggi",
	"Bima",
	"Bau-Bau",
	"Sidoarjo",
	"Blitar",
	"Gunungsitoli",
	"Pagar Alam",
	"Kebumen",
	"Bontang",
	"Mojokerto",
	"Magelang",
	"Payakumbuh",
	"Bukittinggi",
	"Baturaja",
	"Kudus",
	"Sibolga",
	"Tomohon",
	"Tidore",
	"Atambua",
	"Tenggarong",
	"Pariaman",
	"Solok",
	"Sawah Lunto",
	"Padang Panjang",
	"Sabang"
];
exports.listCititesofIndonesian = listCititesofIndonesian;

var listCountry = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Aruba",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bhutan",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"Brunei",
	"Bulgaria",
	"Burkina Faso",
	"Burma",
	"Burundi",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cabo Verde",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo",
	"Democratic Republic",
	"Costa Rica",
	"Cote d'Ivoire",
	"Croatia",
	"Cuba",
	"Curacao",
	"Cyprus",
	"Czechia",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"East Timor",
	"Timor-leste",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Ethiopia",
	"Fiji",
	"Finland",
	"France",
	"Gabon",
	"Gambia",
	"Georgia",
	"Germany",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Holy See",
	"Honduras",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"North Korea",
	"South Korea",
	"Kosovo",
	"Kuwait",
	"Kyrgyzstan",
	"Laos",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macau",
	"Macedonia",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Micronesia",
	"Moldova",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Morocco",
	"Korea",
	"Mozambique",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"North Korea",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestinian Territories",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Romania",
	"Russia",
	"Rwanda",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Sint Maarten",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Korea",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Suriname",
	"Swaziland",
	"Sweden",
	"Switzerland",
	"Syria",
	"Taiwan",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela",
	"Vietnam",
	"Yemen",
	"Zambia",
	"Zimbabwe"
];
exports.listCountry = listCountry;

var validMonth = ["January","February","March","April","May","June","July","August","September","October","November","December"];
exports.validMonth = validMonth;